gyroflow/flowshutter

main.py
sony_multiport.py

Confirm to work!
https://user-images.githubusercontent.com/31283897/153117020-e488e2d0-3e2d-4a63-b7fb-654fb52bef74.mp4

Refactor Sony MTP uart

---

menu.py
vars.py

Introduced a new method to use `*parameter*_range` in `vars.py` to manage parameter options

Add a new function level method to change settings

---

menu.py
oled.py
settings.py
ssd1306.py
vars.py

Ok we have introduced more one bug in the first commit with the goal of simply fixing display version number issue. Luckily all bugs introduced by the first commit are all fixed by the second commit. What a day of trip to rabbit hole!
Orginal idea credits to @PenguinK

Fix display version number issue by updating ssd1306 lib

---

doc/crsf.md
doc/lanc.md
doc/sony.md

Add document for LANC

---

README.md

New open-source design, FC sized, it can be easily stacked with your old 30x30mm size FC.
Can works with the voltage range from 2s up to 6s.

Add link for FC sized design

---

main.py
oled.py
sony_multiport.py
ui.py
vars.py

Change UI update behaviour to polling mode. Max refresh frequency is 25 FPS.
Remove OLED stuff from other places. Two global variables `shutter_state` and `arm_state` are used to pass state information and instruct the OLED to refresh the content.

Refactor UI

---

oled.py
settings.py
vars.py

OLED warning. Also, add a hardcode default settings uploader just in the worst case we lost every setting, we still can bring it back without typing MPY commands.

Add settings corrupt warning

---

README.md

Please take a review, @B-nutze-RR @ElvinC and maybe @AdrianEddy ?

Add development guide

---

README.md

Just to let other people know their shamelessness.

Update Wuxi warning

---

crsf.py
vars.py

200Hz square wave for now. I'll clean this tomorrow.

Add basic audio injection

---

crsf.py
main.py

- Lower CRSF rate to 200hz for better compatibility.
- Add new CRSF packet: marker_packet
- Refactor audio injection function
- Lower injection frequency to 12Hz
TODO: clean all stuffs. Also need to dig into betaflight around RC smoothing.

Imporve audio injection

---

oled.py
ui.py

Per https://github.com/gyroflow/flowshutter/issues/76.

Add starting timeout

---

README.md
ui.py
vars.py

- `Internal SW` -> `Momentary Ground` aka `MMTRY GND`
- `RED V-level` -> `Schmitt trigger` aka `Schmitt trig`
- Also update camera protocol/trigger mechanisms in readme

Cleanup around two simple triggering protocol

---

README.md

Let's see if I got my path right

change path

---

.gitignore
README.md

Also add `pymakr.conf` to `.gitignore`

Update manufacturer info

---

src/sha.json
tools/README.md
tools/gen_sha.py

Fix the wrong sha. Also, `check` of `gen_sha.py` is ready.

Fix wrong sha

---

.gitattributes
.github/workflows/check.yml
src/sha.json
tools/gen_sha.py

The behaviour of `python3 tools/gen_sha.py check` on ubuntu is different to `python tools/gen_sha.py check` on windows. Might be CRLF and LF mess. Skip this for now.

Add ci for check sha

---

tools/gen_sha.py

Add some comments for gen_sha.py

---

.github/workflows/check.yml
src/boot.py
src/ota.py
src/sha.json
src/test1.py

Get changes info by between the `sha.json` of `local` and `upstream`
- `local` => `upstream` (L2U): get update and delete info
- `upstream` => `local` (U2L): get new files info
`text1.py` is for testing the U2L mechanism. Need to be merged with this PR.

Add OTA compare

---

.github/workflows/check.yml
pymakr.conf
src/boot.py
src/ota.py
src/sha.json
src/vars.py
tools/gen_sha.py

- Add new behaviour to `ota.compare()`
- creat `update_list.json` with `update_list` if it is not empty
- creat `delete_list.json` with `delete_list` if it is not empty
- Add a new function of the OTA feature: `fetch`:
- Fetch all files from the select source according to `update_list` and save them to `tmp` dir
- Add testing feature to `boot.py`:
- detect `update_list.json`
- detect `delete_list.json`
- The change of `vars.version` is needed in order to test upcoming update features which will be completed in `boot.py`

Add ota fetch function

---

src/boot.py
src/sha.json

Since `boot.py` is executed before `main.py`, it can be used to handle file replacement during upgrades:
- delete outdated files
- move new files from `/tmp` to root

Add update in boot

---

src/ota.py
src/sha.json
src/vars.py

Fix `SystemExit` error by using `machine.reset()`

Fix soft reset issue

---

src/main.py
src/sha.json
src/sony_multi.py
src/ssd1306.py
src/ui.py

Refactoring sony_multi module into objectified module

Refactor sony multi protocol

---

src/crsf.py
src/crsf_gen.py
src/main.py
src/sha.json
src/sony_multi.py
src/vars.py

Refactoring crsf module into objectified module

Refactor CRSF

---

src/entry.py
src/sha.json
src/ssd1306.py
src/task.py

Use `writevto()` instead of `writeto()`, idel time now is ~1.79ms.

[OLED Driver] Cleanup

---

src/camera.py
src/entry.py
src/settings.py
src/sha.json
src/target.py
src/ui.py
src/vram.py

Will add description for this later.

Add basic bitbang LANC

---

src/camera.py
src/entry.py
src/sha.json
src/target.py
src/ui.py
src/vram.py

Zcam uart protocol spec: https://github.com/imaginevision/Z-Camera-Doc/blob/master/E2/protocol/uart/uart_command.md
Async msg decoding and processing is still WIP, but that's out of scope of this PR.

Add master mode support for ZCAM uart protocol

---

src/camera.py
src/crsf.py
src/entry.py
src/sha.json
src/task.py
src/vram.py

Hide LANC and Zcam test mode for safety reasons....

Fix device settings

---

.github/workflows/build.yml
.gitignore
.vscode/settings.json
README.md
src/sha.json
src/vram.py
tools/build.py
tools/gen_sha.py

Improved the build script and build CI, making it easier to read and maintain.

Improve build script and build ci

---

src/crsf.py
src/entry.py
src/peripherals.py
src/sha.json
src/target.py
src/task.py
src/ui.py
src/vram.py
src/wlan.py

Support "short press" and "long press", "double click" is still WIP.

Async peripherals
