gyroflow/flowshutter

main.py
sony_multiport.py
vars.py

Fix unable to arm FC issue introduced by #6 , also change to use "arm" and "disarm" strings to describe the ARM state of the FC.

fix arm_state issue and display idle info after record ends

---

buttons.py
main.py
menu.py
oled.py
settings.py
target.py
vars.py

This allows to change settings and store them after power off, so next time when the device was powered on, users no more need to change settings to what they want manually.
This also introduced a framework to manage different camera protocols like Sony multiport USB, LANC and more in an easier way.
One thing worth noting is if the shutter was accidentally dropped into the recording state, the unsaved settings might be lost. Further test needed.

Add user setting system

---

ap.py
buttons.py
menu.py
oled.py
vars.py

This PR adds a simple AP mode
The option was hidden under the battery menu. Ro enter this hidden menu, hit "ENT" under battery menu.
"ENT" to toggle AP up and down, "PAGE" to back to battery menu.
AP's ssid is `Flowshutter`, password is `ilovehugo` (for now).

Add AP mode

---

crsf.py
crsf_gen.py
target.py
vars.py

Add a sub-module named `crsf_gen`, which is a CRSF RC packet generator written in native python without any third party lib. It can be re-used on a PC desktop with the purpose of testing CRSF or something.
The audio injection feature is WIP, I'll leave them here as commented.

Use the full function CRSF RC packet generator to replace hardcoding CRSF packet

---

buttons.py
crsf.py
menu.py
vars.py

Allow to start/stop record via flowshutter's button.
In the Sony MTP case, the recording state should still trigger by the camera's recording CMD instead of flowshutter's button. This need to be fixed in the future when the whole OLED update mechanism get refactored.

Add MASTER/SLAVE mode

---

oled.py
ui.py
vars.py

Add a new state `welcome` at powerup. It will automatically transfer to `idle` state after 4sec.
The next step for this topic is to add gyroflow official logo to the OLED lib.

Add welcome state at powerup

---

main.py
ui.py

The `buttons.check(t)` is now a subtask of the `ui.update(t)` task. Save `timer2` which we plan to use later for other functions.

Migrate ui timer task to timer0

---

sony_multiport.py
ui.py

Fix the four-state state machine:
- SLAVE: idle - recording - idle ...
- MASTER/SLAVE:
- idle - starting - recording - stopping - idle
- idle - recording - stopping - idle
- idle - starting - recording - idle
- idle - recording - idle
The two optional transition states were trigger by the ENT button on flowshutter.

Fix MASTER/SLAVE behaviour in Sony MTP

---

wlan.py

Support long and unconventional SSIDs and passwords.
https://github.com/tayfunulu/WiFiManager/pull/15

Update wlan content handler

---

battery.py
oled.py
ui.py
vars.py

The UI task now consists of the following five subtasks in order:
- `battery.read_vol()`
- `buttons.check(t)`
- `_check_oled_()`
- `_check_shutter_state_()`
- `_check_oled_()`
Also, the working state is decoupled from the OLED update incoming parameters, and a new `info` variant is introduced to guide the OLED updater without changing the working state.

Refactor UI system to handle tasks better

---

simple_cam.py
target.py
ui.py
vars.py

This PR introduced two simple camera recording triggering mechanisms:
- `Internal SW`: Use GPIO to mimic the action of a switch short circuit. This mechanism is widely found in various cameras， including but not limited to:
- Canon
- Nikon
- Kinefinity
- BMPCC 4k/6k HDMI recording wire
- `RED V-level`: Use GPIO to change voltage level. Commonly seen on RED cameras. https://support.red.com/hc/en-us/articles/360044301953-DSMC-DSMC2-Remote-Start-Stop

Add internel switch triggering and voltage level triggering

---

oled.py
simple_cam.py
target.py
ui.py
vars.py

- Fix the wrong pin initialization
- Add 1s `starting` and `stopping` state between momentary ground `recording` and `idle` state to avoid potential issue.
- Increase version to v0.50

Fix momentary ground behaviour

---

main.py
target.py
ui.py

Betaflight 4.3.0 RC4 increases the sensitivity to the length of the gap between frames. So now we can't ARM the FC logger correctly due to `RX_loss` and/or `BAD_RX`. Here's the fix:
- Reduce I2C OLED writing time by:
- increase MCU speed to 240MHz
- increase I2C frequency to 800 000
- Reduce CRSF packet sender frequency to 100Hz
- Remove unnecessary OLED update
May lead to increased power consumption, but still needs to be observed.

Fix RX loss issue inctroduced by 4.3 RC4

---

oled.py
ui.py
vars.py

If camera protocol changed, flowshutter should be rebooted so for applying settings.

Add reboot hint for changing camera protocol

---

README.md
simple_cam.py
target.py
ui.py
vars.py

I have only achieved the 3.3V Schmitt trigger, not 5V nor 12V. So rename them all.

Fix misleading info/vars/functions/names around Schmitt Trigger

---

.github/workflows/cla.yml
src/sha.json
tools/LICENSE
tools/gen_sha.py

This is part of the whole "OTA update" plan. Add a "gen_sha.py" script to generate sha1 result for each file and store the result in `sha.json`, which should be loaded to the ESP32.
After this PR, in order to get OTA works, contributors or collaborators should run "python tool/gen_sha.py" locally to generate a corresponding `sha.json` for that commit.
```sh
python tool/gen_sha.py
```

Add sha1 script (PC side)

---

src/sha.json
tools/gen_sha.py

- Delete `sha.json` from the `files` list so to solve the wrong sha1 output.
- Add an option `check` to generate `check_sha` in the root directory, so for using this in CI later.

Add check option (for CI)

---

src/oled.py
src/sha.json
src/ssd1306.py

It's time for a roundup of these OLED driver updates happening today.
The I2C OLED update will cause a ~12ms block in the current code. This is very difficult for us to accept - it will cause an `RX loss` warning on the flight controller and a series of unpredictable consequences.
This PR will split the original OLED refresh action from a full-frame refresh (512 bytes) to a four-sub-frame step-by-step refresh (128 bytes for each).
Although the PR did not improve the blocking situation, the original blocking task has been split into four blocking subtasks, which the queue scheduling method can be used to reorganize these tasks later to alleviate the blocking situation.

[OLED Driver] Split framebuffer by pages

---

src/sha.json
src/ssd1306.py
src/task.py
src/vars.py

This PR makes a small tweak to the OLED driver and adds a small simple scheduler on timer1 to eliminate the blocking problem as described earlier. https://github.com/gyroflow/flowshutter/pull/114
- Split the original `show(self)` into `show(self)` and `show_sub(self, i)`
- `show_sub` is similar to the previous `show`, splitting the entire `framebuffer` by page, the difference is that `show_sub` can perform display operations according to the specified page
- new `show()` is now used to create new `show_sub()` subtasks in `oled_tasklist`
- Add a scheduler on timer1 to replace bare CRSF sender
- the first task is always the CRSF packet sender
- the second task depends on whether `oled_tasklist` is empty, if not it will execute the first task in oled_tasklist at a time, and delete that task …

Add a simple schedular on timer1

---

src/camera.py
src/entry.py
src/settings.py
src/sha.json
src/task.py
src/ui.py

A `rec()` method is added to the all class in `camera.py`, and the `UI` only needs to use its `rec()` method for the abstract camera to complete the REC control of the camera.

Strip camera control behavior from UI logic layer

---

src/entry.py
src/sha.json
src/ssd1306.py
src/target.py

Revert https://github.com/gyroflow/flowshutter/pull/122.
In the previous driver, since `write_data()` was implemented based on the `SoftI2C()`, the clock frequency of the latter was largely dependent on the CPU frequency, which caused a great performance hindrance to the entire project.
Under the chip frequency of 240MHz, the actual clock frequency of I2C SCL can only reach about 370KHz, which makes us have to transfer only half a line of the page (64 bytes) at a time, so as to ensure that there is enough time to process other affairs after the `show_sub()` task. The duration of this idle state is approximately 1.57ms.
This PR rewrites the `write_data()` method which uses the `writeto()` method provided by `I2C()` to replace the `start()`, `write()` and `stop()` methods of the original …

improve ssd1306 driver
